// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assistance_logs.sql

package repository

import (
	"context"
	"database/sql"
)

const createEntryLog = `-- name: CreateEntryLog :one
INSERT INTO assistance_logs (id, log_description, user_id) 
VALUES (?, ?, ?)
RETURNING 
id,
entry_time,
exit_time,
total_daily_minutes,
user_id
`

type CreateEntryLogParams struct {
	ID             string `json:"id"`
	LogDescription string `json:"log_description"`
	UserID         string `json:"user_id"`
}

type CreateEntryLogRow struct {
	ID                string         `json:"id"`
	EntryTime         sql.NullString `json:"entry_time"`
	ExitTime          sql.NullString `json:"exit_time"`
	TotalDailyMinutes sql.NullInt64  `json:"total_daily_minutes"`
	UserID            string         `json:"user_id"`
}

func (q *Queries) CreateEntryLog(ctx context.Context, arg CreateEntryLogParams) (CreateEntryLogRow, error) {
	row := q.db.QueryRowContext(ctx, createEntryLog, arg.ID, arg.LogDescription, arg.UserID)
	var i CreateEntryLogRow
	err := row.Scan(
		&i.ID,
		&i.EntryTime,
		&i.ExitTime,
		&i.TotalDailyMinutes,
		&i.UserID,
	)
	return i, err
}

const getIDFromLastEntryLogByUser = `-- name: GetIDFromLastEntryLogByUser :one
SELECT id
FROM assistance_logs
WHERE user_id = ?
ORDER BY log_date DESC
LIMIT 1
`

func (q *Queries) GetIDFromLastEntryLogByUser(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getIDFromLastEntryLogByUser, userID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateEntryLog = `-- name: UpdateEntryLog :one
UPDATE assistance_logs 
SET exit_time = CURRENT_TIME
WHERE id = ?
RETURNING
id,
entry_time,
exit_time,
total_daily_minutes,
user_id
`

type UpdateEntryLogRow struct {
	ID                string         `json:"id"`
	EntryTime         sql.NullString `json:"entry_time"`
	ExitTime          sql.NullString `json:"exit_time"`
	TotalDailyMinutes sql.NullInt64  `json:"total_daily_minutes"`
	UserID            string         `json:"user_id"`
}

func (q *Queries) UpdateEntryLog(ctx context.Context, id string) (UpdateEntryLogRow, error) {
	row := q.db.QueryRowContext(ctx, updateEntryLog, id)
	var i UpdateEntryLogRow
	err := row.Scan(
		&i.ID,
		&i.EntryTime,
		&i.ExitTime,
		&i.TotalDailyMinutes,
		&i.UserID,
	)
	return i, err
}
