// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assistance_logs.sql

package repository

import (
	"context"
	"database/sql"
)

const createEntryLog = `-- name: CreateEntryLog :one
INSERT INTO assistance_logs (log_description, user_id) 
VALUES (?, ?)
RETURNING 
assistance_logs.id,
assistance_logs.entry_time,
assistance_logs.user_id,
(
    SELECT rh.total_minutes AS required_total
    FROM users u 
    JOIN required_hours rh ON u.required_hour_id = rh.id 
    WHERE u.id = assistance_logs.user_id
),
(
    SELECT CAST(SUM(total_daily_minutes) AS BIGINT) AS total_accumulated
    FROM assistance_logs al 
    WHERE al.user_id = assistance_logs.user_id
)
`

type CreateEntryLogParams struct {
	LogDescription string `json:"log_description"`
	UserID         string `json:"user_id"`
}

type CreateEntryLogRow struct {
	ID               int64          `json:"id"`
	EntryTime        sql.NullString `json:"entry_time"`
	UserID           string         `json:"user_id"`
	RequiredTotal    int64          `json:"required_total"`
	TotalAccumulated int64          `json:"total_accumulated"`
}

func (q *Queries) CreateEntryLog(ctx context.Context, arg CreateEntryLogParams) (CreateEntryLogRow, error) {
	row := q.db.QueryRowContext(ctx, createEntryLog, arg.LogDescription, arg.UserID)
	var i CreateEntryLogRow
	err := row.Scan(
		&i.ID,
		&i.EntryTime,
		&i.UserID,
		&i.RequiredTotal,
		&i.TotalAccumulated,
	)
	return i, err
}

const getLastEntryLogByUser = `-- name: GetLastEntryLogByUser :one
SELECT id, log_date
FROM assistance_logs
WHERE user_id = ?
AND exit_time IS NULL
ORDER BY log_date DESC
LIMIT 1
`

type GetLastEntryLogByUserRow struct {
	ID      int64  `json:"id"`
	LogDate string `json:"log_date"`
}

func (q *Queries) GetLastEntryLogByUser(ctx context.Context, userID string) (GetLastEntryLogByUserRow, error) {
	row := q.db.QueryRowContext(ctx, getLastEntryLogByUser, userID)
	var i GetLastEntryLogByUserRow
	err := row.Scan(&i.ID, &i.LogDate)
	return i, err
}

const updateExitLog = `-- name: UpdateExitLog :one
UPDATE assistance_logs 
SET exit_time = CURRENT_TIME
WHERE assistance_logs.id = ?
RETURNING 
assistance_logs.id,
assistance_logs.entry_time,
assistance_logs.exit_time,
assistance_logs.user_id,
(
    SELECT rh.total_minutes AS required_total
    FROM users u 
    JOIN required_hours rh ON u.required_hour_id = rh.id 
    WHERE u.id = assistance_logs.user_id
),
(
    SELECT CAST(SUM(total_daily_minutes) AS BIGINT) AS total_accumulated
    FROM assistance_logs al 
    WHERE al.user_id = assistance_logs.user_id
)
`

type UpdateExitLogRow struct {
	ID               int64          `json:"id"`
	EntryTime        sql.NullString `json:"entry_time"`
	ExitTime         sql.NullString `json:"exit_time"`
	UserID           string         `json:"user_id"`
	RequiredTotal    int64          `json:"required_total"`
	TotalAccumulated int64          `json:"total_accumulated"`
}

func (q *Queries) UpdateExitLog(ctx context.Context, id int64) (UpdateExitLogRow, error) {
	row := q.db.QueryRowContext(ctx, updateExitLog, id)
	var i UpdateExitLogRow
	err := row.Scan(
		&i.ID,
		&i.EntryTime,
		&i.ExitTime,
		&i.UserID,
		&i.RequiredTotal,
		&i.TotalAccumulated,
	)
	return i, err
}
