// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type RequiredHour struct {
	ID           int64        `json:"id"`
	Type         string       `json:"type"`
	TotalMinutes int64        `json:"total_minutes"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Email          string `json:"email"`
	Password       string `json:"password"`
	RequiredHourID int64  `json:"required_hour_id"`
}
