// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: periods.sql

package repository

import (
	"context"
)

const createPeriod = `-- name: CreatePeriod :one
INSERT INTO periods (name, entry_date, exit_date)
VALUES (?, ?, ?)
RETURNING
id,
name,
entry_date,
exit_date
`

type CreatePeriodParams struct {
	Name      string `json:"name"`
	EntryDate string `json:"entry_date"`
	ExitDate  string `json:"exit_date"`
}

type CreatePeriodRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	EntryDate string `json:"entry_date"`
	ExitDate  string `json:"exit_date"`
}

func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) (CreatePeriodRow, error) {
	row := q.db.QueryRowContext(ctx, createPeriod, arg.Name, arg.EntryDate, arg.ExitDate)
	var i CreatePeriodRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EntryDate,
		&i.ExitDate,
	)
	return i, err
}

const deletePeriods = `-- name: DeletePeriods :exec
DELETE FROM periods
`

func (q *Queries) DeletePeriods(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePeriods)
	return err
}

const getPeriods = `-- name: GetPeriods :many
SELECT id, name FROM periods
`

type GetPeriodsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetPeriods(ctx context.Context) ([]GetPeriodsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPeriodsRow
	for rows.Next() {
		var i GetPeriodsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
