// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package repository

import (
	"context"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, user_id, expires_at)
VALUES (?, ?, datetime('now', '+30 days'))
RETURNING token, user_id, expires_at, is_revoked, created_at, updated_at, deleted_at
`

type CreateRefreshTokenParams struct {
	Token  string `json:"token"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRevoked = `-- name: GetRevoked :one
SELECT is_revoked FROM refresh_tokens
`

func (q *Queries) GetRevoked(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, getRevoked)
	var is_revoked bool
	err := row.Scan(&is_revoked)
	return is_revoked, err
}

const getUserIdFromRefreshToken = `-- name: GetUserIdFromRefreshToken :one
SELECT user_id FROM refresh_tokens
WHERE token = ?
AND is_revoked = 0
AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetUserIdFromRefreshToken(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIdFromRefreshToken, token)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const setRevokedAt = `-- name: SetRevokedAt :exec
UPDATE refresh_tokens
SET is_revoked = 1, updated_at = CURRENT_TIMESTAMP
WHERE token = ?
`

func (q *Queries) SetRevokedAt(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, setRevokedAt, token)
	return err
}
