// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package repository

import (
	"context"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, user_id, expires_at)
VALUES (?, ?, datetime('now', '+30 days'))
RETURNING token, user_id, expires_at, is_revoked, created_at, updated_at, deleted_at
`

type CreateRefreshTokenParams struct {
	Token  string `json:"token"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserIdFromRefreshToken = `-- name: GetUserIdFromRefreshToken :one
SELECT user_id FROM refresh_tokens
WHERE token = ?
AND is_revoked = 0
AND deleted_at IS NULL
AND datetime(expires_at) > datetime('now')
`

func (q *Queries) GetUserIdFromRefreshToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIdFromRefreshToken, token)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const setRevokedAt = `-- name: SetRevokedAt :exec
UPDATE refresh_tokens
SET is_revoked = 1, updated_at = datetime('now')
WHERE token = ?
`

func (q *Queries) SetRevokedAt(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, setRevokedAt, token)
	return err
}
