// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: required_hours.sql

package repository

import (
	"context"
)

const createRequiredHour = `-- name: CreateRequiredHour :one
INSERT INTO required_hours (type, total_minutes) 
VALUES (?, ?)
RETURNING 
id,
type,
total_minutes
`

type CreateRequiredHourParams struct {
	Type         string `json:"type"`
	TotalMinutes int64  `json:"total_minutes"`
}

type CreateRequiredHourRow struct {
	ID           int64  `json:"id"`
	Type         string `json:"type"`
	TotalMinutes int64  `json:"total_minutes"`
}

func (q *Queries) CreateRequiredHour(ctx context.Context, arg CreateRequiredHourParams) (CreateRequiredHourRow, error) {
	row := q.db.QueryRowContext(ctx, createRequiredHour, arg.Type, arg.TotalMinutes)
	var i CreateRequiredHourRow
	err := row.Scan(&i.ID, &i.Type, &i.TotalMinutes)
	return i, err
}

const deleteRequiredHours = `-- name: DeleteRequiredHours :exec
DELETE FROM required_hours
`

func (q *Queries) DeleteRequiredHours(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRequiredHours)
	return err
}

const getRequiredHours = `-- name: GetRequiredHours :many
SELECT id, type FROM required_hours
`

type GetRequiredHoursRow struct {
	ID   int64  `json:"id"`
	Type string `json:"type"`
}

func (q *Queries) GetRequiredHours(ctx context.Context) ([]GetRequiredHoursRow, error) {
	rows, err := q.db.QueryContext(ctx, getRequiredHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRequiredHoursRow
	for rows.Next() {
		var i GetRequiredHoursRow
		if err := rows.Scan(&i.ID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
