// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: required_hours.sql

package repository

import (
	"context"
)

const createRequiredHours = `-- name: CreateRequiredHours :one
INSERT INTO required_hours (type, minutes, created_at, updated_at) 
VALUES (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, type, minutes, created_at, updated_at, deleted_at
`

type CreateRequiredHoursParams struct {
	Type    string
	Minutes int64
}

func (q *Queries) CreateRequiredHours(ctx context.Context, arg CreateRequiredHoursParams) (RequiredHour, error) {
	row := q.db.QueryRowContext(ctx, createRequiredHours, arg.Type, arg.Minutes)
	var i RequiredHour
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Minutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
