// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO users (id, is_admin, name, email, password) 
VALUES (?, 1, ?, ?, ?)
RETURNING 
id,
name,
email
`

type CreateAdminParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateAdminRow struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (CreateAdminRow, error) {
	row := q.db.QueryRowContext(ctx, createAdmin,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	var i CreateAdminRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password, required_hour_id, period_id) 
VALUES (?, ?, ?, ?, ?, ?)
RETURNING 
id
`

type CreateUserParams struct {
	ID             string        `json:"id"`
	Name           string        `json:"name"`
	Email          string        `json:"email"`
	Password       string        `json:"password"`
	RequiredHourID sql.NullInt64 `json:"required_hour_id"`
	PeriodID       sql.NullInt64 `json:"period_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.RequiredHourID,
		arg.PeriodID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const existsAdmin = `-- name: ExistsAdmin :one
SELECT EXISTS (
  SELECT 1
  FROM users
  WHERE is_admin = 1
) = 1
`

func (q *Queries) ExistsAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsAdmin)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getUsersPasswords = `-- name: GetUsersPasswords :many
SELECT password FROM users WHERE is_admin = 0
`

func (q *Queries) GetUsersPasswords(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUsersPasswords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var password string
		if err := rows.Scan(&password); err != nil {
			return nil, err
		}
		items = append(items, password)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateUserPassword = `-- name: ValidateUserPassword :one
SELECT EXISTS (
  SELECT 1
  FROM users
  WHERE is_admin = 0 AND id = ? AND password = ?
) = 1
`

type ValidateUserPasswordParams struct {
	ID       string `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) ValidateUserPassword(ctx context.Context, arg ValidateUserPasswordParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, validateUserPassword, arg.ID, arg.Password)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
