// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO users (id, is_admin, name, email, password) 
VALUES (?, 1, ?, ?, ?)
RETURNING 
id
`

type CreateAdminParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createAdmin,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password, required_hour_id, period_id) 
VALUES (?, ?, ?, ?, ?, ?)
RETURNING 
users.id,
users.name,
users.email,
users.password,
(
  SELECT required_hours.type
  FROM required_hours
  WHERE users.required_hour_id = required_hours.id
),
(
  SELECT required_hours.total_minutes AS hours
  FROM required_hours
  WHERE users.required_hour_id = required_hours.id
),
(
  SELECT periods.name AS period
  FROM periods
  WHERE users.period_id = periods.id
),
(
  SELECT CAST(COALESCE(SUM(total_daily_minutes), 0) AS BIGINT) AS total_hours
  FROM assistance_logs
  WHERE users.id = assistance_logs.user_id
)
`

type CreateUserParams struct {
	ID             string        `json:"id"`
	Name           string        `json:"name"`
	Email          string        `json:"email"`
	Password       string        `json:"password"`
	RequiredHourID sql.NullInt64 `json:"required_hour_id"`
	PeriodID       sql.NullInt64 `json:"period_id"`
}

type CreateUserRow struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	Type       string `json:"type"`
	Hours      int64  `json:"hours"`
	Period     string `json:"period"`
	TotalHours int64  `json:"total_hours"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.RequiredHourID,
		arg.PeriodID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Type,
		&i.Hours,
		&i.Period,
		&i.TotalHours,
	)
	return i, err
}

const existsAdmin = `-- name: ExistsAdmin :one
SELECT EXISTS (
  SELECT 1
  FROM users
  WHERE is_admin = 1
) = 1
`

func (q *Queries) ExistsAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsAdmin)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getActiveUsers = `-- name: GetActiveUsers :many
SELECT DISTINCT users.id, users.name, CAST(time(assistance_logs.entry_time, '-6 hours') AS TEXT) AS entry_time
FROM users
INNER JOIN assistance_logs ON users.id = assistance_logs.user_id
WHERE users.is_admin = 0 
AND users.deleted_at IS NULL
AND assistance_logs.entry_time IS NOT NULL
AND assistance_logs.exit_time IS NULL
AND assistance_logs.log_date = date('now', '-6 hours')
`

type GetActiveUsersRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	EntryTime string `json:"entry_time"`
}

func (q *Queries) GetActiveUsers(ctx context.Context) ([]GetActiveUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveUsersRow
	for rows.Next() {
		var i GetActiveUsersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.EntryTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminIDAndPasswordByEmail = `-- name: GetAdminIDAndPasswordByEmail :one
SELECT id, password
FROM users
WHERE email = ?
AND is_admin = 1
AND deleted_at IS NULL
`

type GetAdminIDAndPasswordByEmailRow struct {
	ID       string `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) GetAdminIDAndPasswordByEmail(ctx context.Context, email string) (GetAdminIDAndPasswordByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminIDAndPasswordByEmail, email)
	var i GetAdminIDAndPasswordByEmailRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}

const getNotAdminUsers = `-- name: GetNotAdminUsers :many
SELECT 
    users.id, 
    users.name, 
    users.email, 
    periods.name AS period, 
    required_hours.type, 
    required_hours.total_minutes AS hours,
    CAST(COALESCE(SUM(assistance_logs.total_daily_minutes), 0) AS BIGINT) AS total_hours,
    users.password
FROM users
INNER JOIN periods ON users.period_id = periods.id
INNER JOIN required_hours ON users.required_hour_id = required_hours.id
LEFT JOIN assistance_logs ON users.id = assistance_logs.user_id
WHERE users.is_admin = 0
  AND users.deleted_at IS NULL
GROUP BY 
    users.id, 
    users.name, 
    users.email, 
    periods.name, 
    required_hours.type, 
    required_hours.total_minutes
ORDER BY users.created_at ASC
`

type GetNotAdminUsersRow struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	Period     string `json:"period"`
	Type       string `json:"type"`
	Hours      int64  `json:"hours"`
	TotalHours int64  `json:"total_hours"`
	Password   string `json:"password"`
}

func (q *Queries) GetNotAdminUsers(ctx context.Context) ([]GetNotAdminUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotAdminUsersRow
	for rows.Next() {
		var i GetNotAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Period,
			&i.Type,
			&i.Hours,
			&i.TotalHours,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersPasswords = `-- name: GetUsersPasswords :many
SELECT password FROM users WHERE is_admin = 0
`

func (q *Queries) GetUsersPasswords(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUsersPasswords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var password string
		if err := rows.Scan(&password); err != nil {
			return nil, err
		}
		items = append(items, password)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateUserPassword = `-- name: ValidateUserPassword :one
SELECT id FROM users
WHERE is_admin = 0 AND password = ?
`

func (q *Queries) ValidateUserPassword(ctx context.Context, password string) (string, error) {
	row := q.db.QueryRowContext(ctx, validateUserPassword, password)
	var id string
	err := row.Scan(&id)
	return id, err
}
